language: node_js
node_js:
  - 12
sudo: false
before_install:
  - npm install -g vue
cache:
  directories:
    - node_modules
script:
  - npm run build
  - mv src/assets/prism-lang-min dist/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  on:
    branch: master
  local_dir: dist
