language: node_js
node_js:
  - 12
sudo: false
before_install:
  - npm install -g vue
  - npm install -g @vue/cli
cache:
  directories:
    - node_modules
script:
  - npm run build
  - mv dist/ docs/
  - mv src/assets/prism-lang-min docs/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  on:
    branch: master
  local_dir: docs
