dist: xenial
language: node_js
node_js:
  - 12
sudo: false
before_install:
  - npm install -g vue
cache:
  directories:
    - node_modules
    
before_script:
  - cd public/data/scripts; python3 css2json.py
script:
  - npm run build

deploy:
  provider: pages
  target_branch: build
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  on:
    branch: master
  local_dir: dist
